apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: file-service
  namespace: chronoflow
spec:
  selector:
    matchLabels:
      app: file-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
