apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsgateway
  namespace: chronoflow
  labels:
    app: wsgateway
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wsgateway
  template:
    metadata:
      labels:
        app: wsgateway
        version: v1
    spec:
      tolerations:
        - key: "node.gke.io/balloon-pod-resize"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: wsgateway
          image: e1241986/wsgateway:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8087
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
            - name: SERVER_PORT
              value: "8087"
            - name: NACOS_HOST
              value: "nacos.chronoflow.svc.cluster.local"
            - name: NACOS_PORT
              value: "8848"
            - name: NACOS_USERNAME
              value: "nacos"
            - name: NACOS_PASSWORD
              value: "nacos"
            - name: PUB_SUB_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: pub-sub
                  key: pub-sub-service-account
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: noti-config
                  key: gcp.project.id
            - name: FIREBASE_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: firebase
                  key: account-json
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 240
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 240
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30